### ISSUE TITLE
Cannot Manage Requests

### ISSUE THREAD

**Issue by Jimmy-John** [grahamgilbert/Crypt-Server#12]
I'm not entirely sure why, but it seems that the 'groupList' table class is causing the table on the "Manage Requests" page to not render on my build.  If I comment out that particular class, everything is rendered just fine.  This doesn't seem specific to my browser, it seems lots of people in my shop have experienced this issue.  But just in case, here is a list of the browsers I've used and have gotten this result:

Firefox 40.0, OS X 10.10.4
Safari 8.0.7, OS X 10.10.4
Chrome 44.0.2403.155, Windows 8.1 x64

**Comment by grahamgilbert** [comment]
Is this still happening? If so, which version are you using?

**Comment by arubdesu** [comment]
This is happening on most recent (ldap, but shouldn't make a difference) docker container as well as master checkout running with dev server. Symptom is that standard user requests key and admin(user with Superuser status and who is auto-approved to view keys) does not see any key requests at the `manage-requests` url behind the Approve requests menu item. Confirmed that request is in the admin interface and associated with the standard user.
