### ISSUE TITLE
Computer Name and Serial Number not displaying properly

### ISSUE THREAD

**Issue by Jimmy-John** [grahamgilbert/Crypt-Server#13]
I was very tempted to combine this with the other manage_requests issue, but the bureaucrat in me wouldn't let me combine issues in a single container.  Currently, the manage_requests code references the_request.computer.serial and the_request.computer.computername to display a the serial and name of a machine related to a request.  However, since the split which caused secrets to be there own model, the correct references are the_request.serial.computer.serial and the_request.secret.computer.computername.

**Comment by grahamgilbert** [comment]
Will happily take a pull request on this, looks like you've got the fix right there!

**Comment by Jimmy-John** [comment]
Forgive me, I am a complete Git[Hub] noob.  I'm still not 100% sure what a Pull Request is and how this site works.  I'm hopefully going to be going over the mechanics of Git as a version control system this weekend.  If you have a moment, and there is a simple four step, explain like I'm 5 process, I'd be more then happy.  We're looking at deploying Crypt, and if I can help out with tweaks here and there that would be amazing.  I'm trying to firm up my Python skills and I'm just now getting into OS X development.

**Comment by clburlison** [comment]
@Jimmy-John Resources for learning Github:
https://www.youtube.com/watch?v=ZLl6k4_J6Mw & 
https://www.afp548.com/2014/08/05/look-less-silly-on-github/ &
https://help.github.com/articles/using-pull-requests/

Github also has a bunch of other really helpful guides but I think the youtube link connects ideas a bit better personally.

To answer your original question a pull request is a process that is started by you "forking" this git repo. Then you modifying the code and submitting it back to the original code base. If you are confused about things I highly recommend jumping into the MacAdmin slack group, http://macadmins.org to sign up. Lots of really smart people that can answer questions hang out in there.

**Comment by grahamgilbert** [comment]
https://help.github.com/articles/using-pull-requests/
