### ISSUE TITLE
Sort of computers on index.html should be by last_checkin

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/Crypt-Server#22]
I think the most frequent case of visiting the site is to verify or retrieve the most recently escrowed secret so that should bubble to the top. I'd assume this could be sorted by changing the current Meta.ordering value to `-last_checkin`(which would require a DB migrate), and I'd assume you want a fallback of computername (to catch when computers are created without dates, since there's no auto-generation of timestamp on manual create - really, it sounds like the trigger would more accurately be on creation/modification of associated secrets... but I'm getting into the weeds a bit). Since we're dealing with relatively small DB sizes the cost may not be too heavy to sort by multiple schema, if this is really the best way to get this to display properly in the index.html template. 

In my testing I tried a couple methods but couldn't get it to behave(at least with sqlite), so leaving this here for now.

**Comment by grahamgilbert** [comment]
Rewording this so I've got it straight - please correct me if I'm misunderstanding:

> The main page does not currently sort by date. It should do this by default.

**Comment by arubdesu** [comment]
Ayup ;)

**Comment by aysiu** [comment]
Am I reading this wrong that the ordering is currently done by serial number?
https://github.com/grahamgilbert/Crypt-Server/blob/e2306a9fc9ec6b578aae5dfc8638a812b2048392/server/models.py#L18

Would it be just a matter of changing that to `last_checkin` instead? Not sure how to make that descending instead of ascending.

**Comment by grahamgilbert** [comment]
Switch the date format in the template to be ISO dates. It’s sorted in JavaScript once the page is loaded.

**Comment by aysiu** [comment]
Forgive my ignorance here—I don't have a ton of experience editing files within a docker container. Is the idea that serial number sorting should stay the default but people who want to sort by date should edit that file every time there's an update to Crypt?

**Comment by grahamgilbert** [comment]
No need to worry about docker. This is straight up editing a Django template.

**Comment by aysiu** [comment]
I'm a total newbie in this regard. I'm running Crypt with docker. So what file am I editing?

**Comment by aysiu** [comment]
@grahamgilbert gave me enough clues, so here's a PR on this:
https://github.com/grahamgilbert/Crypt-Server/pull/56
