### ISSUE TITLE
Check if key exists before adding. 

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/Crypt-Server#25]
I've forked the client app and modified it so that if you want to keep the key locally on the machine as (root read only) you can. After doing so i've noticed every time "checkin" runs it adds the same key to the server. I would like to add a check on the server side so that when a checkin happens, if the information is the same as the information that is already present it doesn't add anything. I want to have a go at this but i'm completely new to Django. Could you point me in the right direction.. basically which file?

cc @keeleysam 
![screenshot 2016-02-22 09 53 03](https://cloud.githubusercontent.com/assets/6865785/13227253/9a5d0660-d94a-11e5-9357-75a94d820747.png)

**Comment by grahamgilbert** [comment]
Something like this in ``def checkin`` (untested, written in a web browser)

```
try:
    secret = Secret.objects.get(computer=computer, secret=recovery_pass(
except Secret.DoesNotExist:
    secret = Secret(computer=computer, secret=recovery_pass, date_escrowed=datetime.now())
    secret.save()
```

And when you say client app - which one do you mean? crypt2? That's the one to be working on if not, the other isn't getting any more dev time.

**Comment by weswhet** [comment]
Great thanks! yeah Crypt2.

**Comment by weswhet** [comment]
@grahamgilbert Here are the changes we ended up making to get it to work... If you want I'll make PR. https://github.com/grahamgilbert/Crypt-Server/compare/master...squarit:master

**Comment by grahamgilbert** [comment]
I think you'll want to limit that uniqueness to the type of secret too. It's not beyond the realms of possibility to have the same admin password and firmware password (for example).
