### ISSUE TITLE
Date Stored Sort Out of order. 

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/Crypt-Server#26]
Looks like it's set to base the order off of the first number in the day value not the whole number. so it thinks 9 > 14. 

![screen shot 2016-03-14 at 5 09 29 pm](https://cloud.githubusercontent.com/assets/6865785/13763963/b043360c-ea07-11e5-8e96-76d1dbfceb55.png)

**Comment by grahamgilbert** [comment]
The table sorts on the display date. We'll need to do something like was done in Sal.

**Comment by arubdesu** [comment]
dupe of #22?
