### ISSUE TITLE
docs? encryption of DB for at least 1 backend

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/Crypt-Server#3]
Currently no encryption is performed on the entries in the DB to protect the contents from potential local/backup archive access. I'm looking at storing other secrets, and If postgresql is the current favorite database backend to integrate, I'm looking for at least setup instructions to encrypt it. We probably can leave out sqlite, but perhaps MySQL could get docs as well.

**Comment by grahamgilbert** [comment]
It would probably be better to encrypt at the ORM level to make it work with all databases. In a thirty second Google, I found this: https://github.com/defrex/django-encrypted-fields

Need to look at how we'd migrate existing keys though.

**Comment by grahamgilbert** [comment]
I think I'm going to http://django-extensions.readthedocs.org/en/latest/index.html as it's a pretty big project and seems well supported. I think I've got enough of a handle on migrations now to be able to do this. He said confidently, after spending a whole day updating to Django 1.8...

**Comment by grahamgilbert** [comment]
This is implemented. Existing secrets will be encrypted when the database migration happens. Run ``$ python generate_keyczart.py`` prior to performing the migration as per the latest [upgrade doc](https://github.com/grahamgilbert/Crypt-Server/blob/master/docs/July_2015_Update.md#docker)
