### ISSUE TITLE
Installation on Ubuntu 14.0.4 launches apache default page rather than Crypt Server

### ISSUE THREAD

**Issue by tempusthales** [grahamgilbert/Crypt-Server#33]
I followed all the steps provided in the doc for Installation on Ubuntu 14.04 LTS, and at the end of the process I went to load the server and I receive the Apache Default page rather than the Crypt Server.

crypt.conf: https://gist.github.com/tempusthales/fadccba90474c497f237a67bbfe242d7#file-crypt-conf

other than that, the rest of the files are configured the way the doc says.  When I point my browser to the server I receive the Apache2 Ubuntu Default Page rather then the crypt server.

**Comment by grahamgilbert** [comment]
And dfw-deskeng.localhost is a resolvable address in DNS for this server?

**Comment by grahamgilbert** [comment]
Also see http://stackoverflow.com/questions/23713061/virtualhost-always-returns-default-host-with-apache-on-ubuntu-14-04

**Comment by tempusthales** [comment]
well that is a placeholder name, the real server name resolves to the
server in question.

On Thu, May 26, 2016 at 3:03 AM, Graham Gilbert <notifications@github.com>
wrote:

> And dfw-deskeng.localhost is a resolvable address in DNS for this server?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grahamgilbert/Crypt-Server/issues/33#issuecomment-221804181>
>



-- 
Gilbert J. Palau
gilbertpalau@gmail.com
http://gilbertopalau.com

**Comment by tempusthales** [comment]
This is what my apache2 error log looks like:

`[Wed May 25 16:40:10.302387 2016] [mpm_event:notice] [pid 2247:tid 140635913041792] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed May 25 16:40:10.302532 2016] [core:notice] [pid 2247:tid 140635913041792] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 25 16:40:11.598250 2016] [mpm_event:notice] [pid 2247:tid 140635913041792] AH00491: caught SIGTERM, shutting down
[Wed May 25 16:40:12.664241 2016] [mpm_event:notice] [pid 2413:tid 140010632509312] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed May 25 16:40:12.665934 2016] [core:notice] [pid 2413:tid 140010632509312] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 25 16:56:14.249974 2016] [mpm_event:notice] [pid 2413:tid 140010632509312] AH00493: SIGUSR1 received.  Doing graceful restart
apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/wsgi.load: Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server: /lib/x86_64-linux-gnu/libm.so.6: symbol __strtold_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
[Wed May 25 16:57:08.485124 2016] [core:warn] [pid 10414:tid 139853221750656] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Wed May 25 16:57:08.485852 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed May 25 16:57:08.485884 2016] [core:notice] [pid 10414:tid 139853221750656] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 25 16:57:18.907400 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Wed May 25 16:57:18.972549 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed May 25 16:57:18.972608 2016] [core:notice] [pid 10414:tid 139853221750656] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 25 17:00:03.841448 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Wed May 25 17:00:03.901940 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed May 25 17:00:03.901974 2016] [core:notice] [pid 10414:tid 139853221750656] AH00094: Command line: '/usr/sbin/apache2'
[Thu May 26 13:37:20.428026 2016] [mpm_event:notice] [pid 10414:tid 139853221750656] AH00491: caught SIGTERM, shutting down
[Thu May 26 13:37:21.223068 2016] [mpm_event:notice] [pid 13047:tid 140463763208064] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Thu May 26 13:37:21.223350 2016] [core:notice] [pid 13047:tid 140463763208064] AH00094: Command line: '/usr/sbin/apache2'
[Thu May 26 13:37:43.624413 2016] [mpm_event:notice] [pid 13047:tid 140463763208064] AH00491: caught SIGTERM, shutting down
[Thu May 26 13:37:56.795055 2016] [mpm_event:notice] [pid 963:tid 140643436795776] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Thu May 26 13:37:56.808408 2016] [core:notice] [pid 963:tid 140643436795776] AH00094: Command line: '/usr/sbin/apache2'
[Thu May 26 13:58:42.518321 2016] [mpm_event:notice] [pid 963:tid 140643436795776] AH00493: SIGUSR1 received.  Doing graceful restart
[Thu May 26 13:58:42.582213 2016] [mpm_event:notice] [pid 963:tid 140643436795776] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Thu May 26 13:58:42.582281 2016] [core:notice] [pid 963:tid 140643436795776] AH00094: Command line: '/usr/sbin/apache2'`

Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server  ?

**Comment by grahamgilbert** [comment]
Looks like it. Paging @rbuzzell who actually wrote this documentation.

**Comment by rbuzzell** [comment]
I'm not an expert on apache or wsgi, but I'll try what I can.

Which version of apache are you running?

        Order deny,allow
        Allow from all
Looks like Apache 2.2 syntax, which becomes 

`Require all granted`

in Apache 2.4
https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html
That might cause some issues.

I also don't see either of these lines which direct the wsgi process on where to run. I don't know if those can be inside of the `<virtualhost *:80>` block, but it won't work without these.

    WSGISocketPrefix /var/run/wsgi
    WSGIPythonHome /usr/local/crypt_env

**Comment by rbuzzell** [comment]
@tempusthales did this help at all?

**Comment by tempusthales** [comment]
gave up on the crypt server and went with another solution…

On Mon, Jun 13, 2016 at 8:49 AM, Ryan Buzzell <notifications@github.com>
wrote:

> @tempusthales <https://github.com/tempusthales> did this help at all?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grahamgilbert/Crypt-Server/issues/33#issuecomment-225585919>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACVXx46t8jY6HvIVKtnGKH7wcEqIoRRIks5qLV_RgaJpZM4Im5IB>
> .
>



-- 
Gilbert J. Palau
gilbertpalau@gmail.com
http://gilbertopalau.com
