### ISSUE TITLE
14.04 instructions lead to error 500

### ISSUE THREAD

**Issue by knl** [grahamgilbert/Crypt-Server#38]
Hi,
I tried following the instruction on how to get crypt-server running on 14.04 (because I can't use docker, due to proxy issues). After a bit of struggling, I got crypt-server to run, but when I access it via browser, I get this:

```
Unknown parameters: debug
Request Method:	GET
Request URL:	https://crypt.fpprod.corp/login/?next=/
Django Version:	1.10
Exception Type:	ImproperlyConfigured
Exception Value:	
Unknown parameters: debug
Exception Location:	/usr/local/crypt_env/local/lib/python2.7/site-packages/django/template/backends/base.py in __init__, line 29
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/local/crypt_env/lib/python2.7',
 '/usr/local/crypt_env/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/local/crypt_env/lib/python2.7/lib-tk',
 '/usr/local/crypt_env/lib/python2.7/lib-old',
 '/usr/local/crypt_env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/local/crypt_env/local/lib/python2.7/site-packages',
 '/usr/local/crypt_env/lib/python2.7/site-packages',
 '/usr/local/crypt_env',
 '/usr/local/crypt_env/crypt']
Server time:	Thu, 2 Mar 2017 17:36:55 +0100
```
(this is with debug enabled).
Does anyone have any ideas?

Apart from this issue, I couldn't get `pip install -r crypt/setup/requirements.txt` step to work, as there is no 1.6.8 version of django-extensions. There is 1.6.7 and 1.7.1, so I followd the steps from Dockerfile to install django-extensions.

**Comment by grahamgilbert** [comment]
I would guarantee that's not the whole error. The whole one would give you a line number.

**Comment by porkcube** [comment]
Seeing the same thing with an install on CentOS7.  Having either `Debug = False` (default) or `Debug = True` produces same error about "Unknown parameters: debug".  Right now only running with `python manage.py runserver 0.0.0.0:8000` for testing.

Traceback: http://dpaste.com/0YTWCBP

**Comment by grahamgilbert** [comment]
I won’t be able to reproduce on centos as my
Org only uses Ubuntu. Any reason you can’t use the docker image?

**Comment by porkcube** [comment]
Yeah we're the opposite - RHEL/CentOS

Have similar proxy issues as OP with running Docker, also just trying to stand it up for testing right now.

I'll have some more time to poke at it over the next few days and report back if I can get past this error.

**Comment by porkcube** [comment]
OK I narrowed down the problem specifically with this 500 error - exact same thing happened on an Ubuntu 14.0.5 install in VMWare so it's not an OS/distro thing, it turns out it's an example-settings.py thing.

I started copying things out of the settings.py from the Docker image block-by-block and sure enough the 500s stopped, eventually.

It appears to be the `TEMPLATES` section of the example-settings.py file, specifically `'APP_DIRS':True,` missing from the non-Docker example-settings.py and I also moved `'debug': DEBUG,` to match

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert your TEMPLATE_DIRS here
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS':True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]
```

This got it working, though now getting 404s for any .js and .css files, but that's a separate issue

**Comment by grahamgilbert** [comment]
Feel free to PR this if you got it working

**Comment by porkcube** [comment]
Submitted!
