### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/Crypt-Server#4]
API access, more about validation than actually extracting data. I'd rather not ship keys out from the server, ever, no matter how much it could come in handy. More about validating it got escrowed/rolled

**Comment by arubdesu** [comment]
Further, would be nice to let approvers grant (one-time?) view access via the API

**Comment by grahamgilbert** [comment]
Hmm, the api framework I used in Sal gives access to the full model. It would probably be easier to just build in the checks you need. I assume this is related to key rotation?

**Comment by arubdesu** [comment]
To ensure the key actually was rolled post-access would be one of the most important applications, yes. There are no good programmatic ways to check things happened as they should locally that I know of http://www.johnkitzmiller.com/blog/automatically-re-issue-individual-filevault-2-recovery-keys-after-single-use-with-the-casper-suite/

**Comment by grahamgilbert** [comment]
I think key rotation is something that should be initiated from the server. I'll get my thinking cap on.

**Comment by arubdesu** [comment]
I think auth plugin being able to capture a users creds from the login window(among other simpler mechanisms, all of which assume network access...) to be able to rotate anytime makes the reliance on shipping anything out from the server moot/less necessary.

**Comment by grahamgilbert** [comment]
Ok, I'll leave you to write the auth plugin! Ultimately, I'd like to get rid of the client all together and just use an Auth plugin but I think that's a way off.

**Comment by grahamgilbert** [comment]
I think we've solved this in roundabout ways. Let me know if you still want to work on this.
