### ISSUE TITLE
allow password secret type to be denoted as such at time of escrow

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/Crypt-Server#6]
I'd like to encrypt with a static password(ideally laid down via the new DEP-delivered hidden admin profile?) and then roll it once we add the assigned AD user. We'd therefore be hoping to escrow a random new password to crypt, separating the computer into a separate table, perhaps based on serial?

**Comment by grahamgilbert** [comment]
Sorry, I'm not sure I follow what you're asking here?

**Comment by arubdesu** [comment]
Allow other secrets, for one our local admin's password(the firmware password would be a further application), to be escrowed to crypt and be associated with the same record as the FV2 key. Same workflows around access control and protected DB storage-slash metadata/approval-only API access. I know, a lot of words that may not be making this clearer/seems like feature bloat...

**Comment by grahamgilbert** [comment]
So really the request is to separate the key and computer models - which would allow more than one key / secret per computer.

**Comment by arubdesu** [comment]
yes, and whatever would need to happen to maintain the same workflows around approval to each separate class of keys/secrets would be great. (I had been overlooking firmware password, which is now bundled/programmatically accessible with the built-in firmwarepasswd binary on 10.10+. There may be a stable workflow around the 'seed', which would make it so the actual password never needs to get shipped out from the server when rotating.)

**Comment by grahamgilbert** [comment]
So I've split out the models out. Now just need to write some views to allow sending data with the 'secret_type' field. Can't be bothered to update the client just yet, so it will probably be another endpoint for simplicity.

**Comment by arubdesu** [comment]
I'm revisiting this soon, so I wanted to alter the subject to reflect the only remaining alterations required, which is to allow the secret to be denoted as a password at escrow time.

**Comment by grahamgilbert** [comment]
You can?

https://github.com/grahamgilbert/Crypt-Server/blob/master/server/views.py#L221-L224

**Comment by arubdesu** [comment]
if I'm not mistaken (and I've tried a few permutations of the below example code) there's no value that I can submit for secret_type when cURL'ing to the checkin URL and have it succeed in displaying as I'd expect.
```
import subprocess
import urllib

password, serial, macname, theurl = 'supersekrit', 'MYSERIAL', 'mycompy', 'https://crypt.url'
mydata = [('recovery_password', password), ('serial', serial), ('macname', macname), ('username', 'rotate_bot'), ('secret_type', 'password')]
mydata = urllib.urlencode(mydata)
cmd = ['/usr/bin/curl', '-fsSL', '--data', mydata, theurl + "/checkin/"]
task = subprocess.Popen(cmd, stdout=subprocess.PIPE,
stderr=subprocess.PIPE)
(output, error) = task.communicate()
if task.returncode != 0:
    print 'Encountered error on escrow: %s.' % error
```
![screenshot 2016-01-10 14 21 05](https://cloud.githubusercontent.com/assets/388808/12223445/a64f8f4a-b7a5-11e5-95ad-8e4ba0de2f2d.png)

**Comment by grahamgilbert** [comment]
Have you looked in django admin? I'd put money on this being an issue with the template...

**Comment by arubdesu** [comment]
Doesn't look like that's the issue
![screenshot 2016-01-10 14 27 08](https://cloud.githubusercontent.com/assets/388808/12223460/3f29805e-b7a6-11e5-992f-4060544bd1bf.png)

**Comment by grahamgilbert** [comment]
Ok, I'll have a look tomorrow. Not sure why it's not working (and I'm reasonably sure I tested this when it was implemented last year).

**Comment by arubdesu** [comment]
Figured it out, it's where we're saving it: https://github.com/grahamgilbert/Crypt-Server/blob/master/server/views.py#L237 is supposed to be `secret = Secret(computer=computer, secret=recovery_pass, secret_type=secret_type, date_escrowed=datetime.now())`, currently it omits setting the secret_type. Shall I PR?

**Comment by arubdesu** [comment]
This was merged a while back, closing.
