### ISSUE TITLE
Help with migrating from Crypt2

### ISSUE THREAD

**Issue by patm80** [grahamgilbert/Crypt-Server#70]
Hello,

I'm having some problems migrating my Crypt2 docker container to Crypt3. I know this is not an issue per se but I'm hoping I can find some advice here.
I'm able to run my new Crypt3 container using the provided documentation here (https://github.com/grahamgilbert/Crypt-Server/blob/master/docs/Docker.md).
If I provide my old keys and the new encryption key in the docker run command I can access my crypt content.
My question now is what needs to be done to migrate from Crypt2 to Crypt3. What has to be migrated and in which way do I have to handle my old keys?
Also what is the best way to handle not having the new encrypion key in the run command?

Sorry if this is a stupid questions, just having some problems understanding.

Thanks,
Patrick

**Comment by clburlison** [comment]
Hey Patrick,
What issue are you actually running into? Your statement above is quite confusing to follow it sounds like you were able to successfully upgrade to crypt3 so if you have an error from the logging that would be helpful.

> What has to be migrated
Just the database going from crypt2 to crypt3 as this is a one time process that re-encrypts the recovery keys. Once it is complete you can remove the crypt2 keyset.

> best way to not have the encryption key in the run command
Unfortunately this will depend on your environment. You could use something like docker-compose + Vault for storing the key or put the key in a .env file. See the following link for some examples https://stackoverflow.com/a/42151570

**Comment by patm80** [comment]
Hey Clayton,

thanks for your quick response! Ok so maybe I'm just confusing something... So the Container works when I run it with the old keys with the -v parameter and the  new key with the -e FIELD_ENCRYPTION_KEY parameter. This would be the respective section:

> You should pass in both your old encryption keys (e.g. -v /somewhere/on/the/host:/home/docker/crypt/keyset) and the new one (see below) for the first run to migrate your keys. After the migration you no longer need your old encryption keys.

Whats confusing me is that I dont understand when I dont need the old keys anymore or more precisely I'm not sure what I have to do so I dont need my old keys anymore.

> Just the database going from crypt2 to crypt3 as this is a one time process that re-encrypts the recovery keys. Once it is complete you can remove the crypt2 keyset.

So If I ran the container with the new recovery key and the old recovery key is there any other action I need to take to finish the migration? Because as you said, I would agree it sounds to me that I've already migrated.. 

Thanks so much and sorry for the confusion,
Patrick

**Comment by clburlison** [comment]
Thanks that's the missing information. Based off your last reply you have successfully migrated from crypt-server v2 to crypt-server v3. This means you no longer need your old encryption keys. I personally would store these old keys in a backup somewhere in case you have old database backups you need to restore at some point in the future.

For example this is what you ran to do your migration from v2 to v3
```bash
docker run -d --name="Crypt" \
--restart="always" \
-v /somewhere/else/on/the/host:/home/docker/crypt/crypt.db \
-e FIELD_ENCRYPTION_KEY='yourencryptionkey' \
-p 8000:8000 \
macadmins/crypt-server
```

Now that the migration is done you can exclude passing the old encryption keys
```bash
docker run -d --name="Crypt" \
--restart="always" \
-e FIELD_ENCRYPTION_KEY='yourencryptionkey' \
-p 8000:8000 \
macadmins/crypt-server
```

The old keyset files can be removed off the server.

**Comment by patm80** [comment]
Hey Clayton,

first of all thanks a lot for your help! This answers my question perfectly. I will be testing my migration today and I'll get back to you so you can close this issue.

Thanks so much,
Patrick

**Comment by patm80** [comment]
So I ran this command again:

> docker run -d --name="Crypt" \
--restart="always" \
-v /somewhere/else/on/the/host:/home/docker/crypt/crypt.db \
-e FIELD_ENCRYPTION_KEY='yourencryptionkey' \
-p 8000:8000 \
macadmins/crypt-server

After that I took a look at the container logs and saw the following output
> Operations to perform:
  Apply all migrations: admin, auth, contenttypes, server, sessions, sites
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

I applied those changes using the manage.py script and all seems fine. One thing I'm still having trouble understanding is what do I do with the container running with the old crypr-db as a parameter?
I thought I just have to rerun the command without the -v command as you described it. But seeing that a container with the same name already exists I get the expected error "Conflict container name".
What am I missing here? Because if I delete this container and rerun it without the -v parameter my changes/migration is gone...

I don't have that much experience yet with docker so sorry for all those questions ... 

Thanks,
Patrick

**Comment by patm80** [comment]
Maybe my question is not very clear ... How do I rerun the docker run command
`docker run -d --name="Crypt" \
--restart="always" \
-e FIELD_ENCRYPTION_KEY='yourencryptionkey' \
-p 8000:8000 \
macadmins/crypt-server`
without the old keys, if I already created a container with the same name for the migration?

Thanks, 
Patrick

**Comment by grahamgilbert** [comment]
Delete the old container then. The only things you care about are your database and your field encryption key. The app container is disposable.

**Comment by patm80** [comment]
Alright, thanks a lot for the help!

Best,
Patrick

**Comment by clburlison** [comment]
@patm80 Can this issue be closed? I'm assuming all your answers have been answered at this time.

**Comment by patm80** [comment]
Yeah, 
it can be closed. 
Thanks again!
