### ISSUE TITLE
Problem installation key

### ISSUE THREAD

**Issue by davidkast** [grahamgilbert/Crypt-Server#75]
Hi, I find your project very interesting and I am installing it.
I encountered the following problem:
When launching the command:
`python3 manage.py syncdb`
The following error appears:
**Fernet key must be 32 url-safe base64-encoded bytes.**
[error](http://floomby.io/s/280619/7UV2YBeC)

The key must be added in the file settings.py as a variable:
FIELD_ENCRYPTION_KEY = "blablablablablablablablabla"
or
the line in the system_settings.py file must be modified
FIELD_ENCRYPTION_KEY = os.environ.get ("FIELD_ENCRYPTION_KEY", "blablablablablablablablabla")
[settings.py](http://floomby.io/s/280619/cJ90flb2) 
[system_settings.py](http://floomby.io/s/280619/6V04vs4M) 

Thanks for the help.

**Comment by grahamgilbert** [comment]
This is in the docs at https://github.com/grahamgilbert/Crypt-Server/blob/master/docs/Docker.md#generating-an-encryption-key

Modifying system settings is not recommended.
