### ISSUE TITLE
How to change the timezone of docker?

### ISSUE THREAD

**Issue by nieivan** [grahamgilbert/Crypt-Server#78]
Hi, 
I tried to adjust the timezone of docker with the following methods, but both of them don't work
1. -v /etc/localtime:/etc/localtime:ro
2. install tzdate, and RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime.
3. ENV TZ=Asia/Shanghai

any suggestions?

**Comment by grahamgilbert** [comment]
https://github.com/grahamgilbert/Crypt-Server/blob/7e68d48faf6d1477d5e383d18c46b1956bd25d98/docker/settings_import.py#L54 Is the setting you need to set. You do not say if you are overriding your settings file completely. If so you need to ensure system_settings is imported or set it explicitly in your settings.

**Comment by nieivan** [comment]
e...how to import system_settings in docker? I tried to find the instruction but failed... sorry I'm new to this, thanks. @grahamgilbert

**Comment by grahamgilbert** [comment]
It would help if you stated you entire setup, then I’m not guessing.

**Comment by nieivan** [comment]
I just setup a docker Crypt-server with following the instruction of basic usage in this guide (https://github.com/grahamgilbert/Crypt-Server/blob/master/docs/Docker.md), most of settings are default.

**Comment by grahamgilbert** [comment]
Post your settings file. Something is wrong if it’s not working.

**Comment by nieivan** [comment]
I Resolved this with the following steps, is it OK from your perspective? @grahamgilbert 

1. Install tzdata in Crypt container
`apk add tzdata`

2. add env TZ='Asia/Shanghai' when run docker
```
docker run -d --name="Crypt" \
--restart="always" \
-v /somewhere/dbfile:/home/docker/crypt/crypt.db \
-e FIELD_ENCRYPTION_KEY='encryption key' \
-e TZ='Asia/Shanghai' \
-p 8000:8000 \
macadmins/crypt-server
```

3. restart Crypt container
`docker container restart Crypt`

**Comment by grahamgilbert** [comment]
Odd if that’s required now. Feel like making a pull request to add that?


________________________________

**Comment by nieivan** [comment]
Perhaps I should to try the general approach again for double check, is the step correct?

1. add getenv("TZ") part to ./fvserver/settings.py。
2. mount settings.py to docker with docker run -v ./settings.py
3. do check.

**Comment by nieivan** [comment]
failed, here is my settings.py file...

```
from fvserver.system_settings import *
from fvserver.settings_import import *
import os
from os import getenv
import locale

# Django settings for fvserver project.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        "NAME": os.path.join(
            PROJECT_DIR, "crypt.db"
        ),  # Or path to database file if using sqlite3.
        "USER": "",  # Not used with sqlite3.
        "PASSWORD": "",  # Not used with sqlite3.
        "HOST": "",  # Set to empty string for localhost. Not used with sqlite3.
        "PORT": "",  # Set to empty string for default. Not used with sqlite3.
    }
}

host = None
port = None

if "DB_HOST" in os.environ:
    host = os.environ.get("DB_HOST")
    port = os.environ.get("DB_PORT")

elif "DB_PORT_5432_TCP_ADDR" in os.environ:
    host = os.environ.get("DB_PORT_5432_TCP_ADDR")
    port = os.environ.get("DB_PORT_5432_TCP_PORT", "5432")

if host and port:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASS"],
            "HOST": host,
            "PORT": port,
        }
    }

if getenv("TZ"):
    if "/" in getenv("TZ"):
        TIME_ZONE = getenv("TZ")
    else:
        TIME_ZONE = "Asia/Shanghai"
elif getenv("TZ"):
    TIME_ZONE = getenv("TZ")
else:
    TIME_ZONE = "Asia/Shanghai"
```

**Comment by grahamgilbert** [comment]
That looks fine. All of my servers run UTC which is why I’ve probably not seen this. Please do a PR to add the missing tzdata package to the dockerfile.

**Comment by nieivan** [comment]
Sure, created a PR, added tzdata installation in dockerfile.
