### ISSUE TITLE
Is it possible to export audit logs to the 3rd party log mgmt. system, like SIEM?

### ISSUE THREAD

**Issue by nieivan** [grahamgilbert/Crypt-Server#82]
Hello, 

where is the audit log in the docker? Is it possible to export audit logs to the 3rd party log mgmt. system, like SIEM?  thanks.

**Comment by clburlison** [comment]
https://success.docker.com/article/logging-best-practices

Most of the built in drivers are quite easy to configure.

![Screen Shot 2019-09-16 at 9 17 27 AM](https://user-images.githubusercontent.com/2831320/64965543-d268f800-d862-11e9-807f-2dd00264feee.png)

**Comment by grahamgilbert** [comment]
There is no audit log. You would need to submit a PR that prints out access requests to stdout for ingestion elsewhere.
