### ISSUE TITLE
there is no authentication on interface /checkin

### ISSUE THREAD

**Issue by nieivan** [grahamgilbert/Crypt-Server#89]
there is no authentication on interface /checkin, which means anyone could submit any record to database, which might causes dirty key records issue

**Comment by justforhack** [comment]
Hi, can you tell me what does interface /checkin used for? And what does a request to interface /checkin look like?

**Comment by grahamgilbert** [comment]
It’s used for key submission.

**Comment by justforhack** [comment]
Ok, so what is the impact when an unauthenticated user submit a key to the server? Gain access or memory corruption? Or corrupt another user authentication?

**Comment by erikng** [comment]
Isn't that up to you to figure out, "justforhack"?

**Comment by grahamgilbert** [comment]
There is no known impact. If you find something please open an issue.

**Comment by justforhack** [comment]
@erikng Nice guest! Yeah, I am a pentester and also a security manager in a small company. We are using your service but we have used it for a long time when crypt-server just published a few days without any update. So I want to ask that if there was any security issue which has a security impact to we can know and fix it! (We are so lazy to it). Sorry if bad English.
