### ISSUE TITLE
Docker build broken due to "Double requirement given" in requirements.txt

### ISSUE THREAD

**Issue by bruienne** [grahamgilbert/Crypt-Server#9]
While checking on the crypt-server build status on Docker Hub I noticed the most recent build was broken. Running it again gives the following error:

`Double requirement given: django-bootstrap3==5.4.0 (from -r /home/docker/crypt/setup/requirements.txt (line 11)) (already in django-bootstrap3==5.4.0 (from -r /home/docker/crypt/setup/requirements.txt (line 3)), name='django-bootstrap3')`

It appears that `django-bootstrap3` is included twice - once on [line 3](https://github.com/grahamgilbert/Crypt-Server/blob/master/setup/requirements.txt#L3) and once on [line 11](https://github.com/grahamgilbert/Crypt-Server/blob/master/setup/requirements.txt#L11) - that's probably a typo I'm guessing which appears to have been part of 025b639. Wanted to bring it to your attention, can send PR if you prefer.

/cc @arubdesu

**Comment by grahamgilbert** [comment]
A PR is fine - stuck in an airport with only my phone at the moment. 

Graham Gilbert

**Comment by bruienne** [comment]
I'll badger @arubdesu first since he broke it in the first place =)
