### ISSUE TITLE
500 error at /checkin (and unverified XSS)

### ISSUE THREAD

**Issue by justforhack** [grahamgilbert/Crypt-Server#92]
When I access the `/checkin` endpoint, the server will give me a 500 error code:

```http
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Date: Wed, 24 Jun 2020 14:53:27 GMT
Server: nginx
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Connection: Close
```
I don't know why this happens but other endpoints still working very well, no bugs!
Also, I found an unverified XSS since I can't test it with my server when my server has been taken down for some fixes!
The following snippet is taken from `/server/views.py`:
```python
        serial_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            machine["serial"],
        )

        computername_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            machine["computername"],
        )

        info_button = '<a class="btn btn-info btn-xs" href="%s">Info</a>' % (
            reverse("server:computer_info", args=[machine["id"]])
        )

        list_data = [
            serial_link,
            computername_link,
            machine["username"],
            formatted_date,
            info_button,
        ]
        return_data["data"].append(list_data)

    return JsonResponse(return_data)
```

The following lines show that XSS is possible if the user sets his `computername` to `<script>alert(1)</script>`:

```python
        computername_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            machine["computername"],
```
The output will become like this:
```html
<a href="..."><script>alert(1)</script></a>
```

(Sorry if bad English)

**Comment by grahamgilbert** [comment]
If you enable debug mode in your `settings.py` you will get the full traceback.

**Comment by justforhack** [comment]
Haven't checked yet since my server is still in fixing mode, but thanks, I will check back soon! Also, what about the bug?

For fix:
```html
        serial_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
[            machine["serial"].replace('<', '&lt;'),
        )

        computername_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            machine["computername"].replace('<', '&lt;'),
        )

        info_button = '<a class="btn btn-info btn-xs" href="%s">Info</a>' % (
            reverse("server:computer_info", args=[machine["id"]])
        )

        list_data = [
            serial_link,
            computername_link,
            machine["username"],
            formatted_date,
            info_button,
        ]
        return_data["data"].append(list_data)

    return JsonResponse(return_data)
``` 
It would be better if you create a function just for filtering unsafe characters.

**Comment by justforhack** [comment]
Hi, can you also give me a full list of Crypt Server endpoints? Thanks

**Comment by grahamgilbert** [comment]
https://github.com/grahamgilbert/Crypt-Server/blob/master/server/urls.py

**Comment by shelld3v** [comment]
Awesome! So ... should ... should ... we ... ... ... close this ...? Or ... or ... ...!

**Comment by grahamgilbert** [comment]
I feel like there should be a built in method in Django to do this, but I have zero time to spend on this right now.

**Comment by grahamgilbert** [comment]
Yes now I’ve woken up this should just be put in the base template. An easy PR for your first https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#autoescape

**Comment by grahamgilbert** [comment]
And what about the 500 error? This sounds like it should be easy enough for you to replicate?

**Comment by shelld3v** [comment]
Yeah, maybe, since I am going to re-build and re-run the server (still using Crypt Server).

>I feel like there should be a built in method in Django to do this, but I have zero time to spend on this right now.

Why you don't have time?

**Comment by shelld3v** [comment]
I also think we can close this now!

**Comment by grahamgilbert** [comment]
> Yeah, maybe, since I am going to re-build and re-run the server (still using Crypt Server).
> 
> > I feel like there should be a built in method in Django to do this, but I have zero time to spend on this right now.
> 
> Why you don't have time?

Because I have a day job and open source doesn’t pay the bills.

**Comment by justforhack** [comment]
What is your day job? I'm so excited to know! (Guess it's Developer) And if you have any other open-source projects that you don't have time to update, feel free to invite me for help (still don't understand why you just create this huge project although don't have any time to work with it:)! I also have a day job, it's Security Engineer, and very want to work with open-source projects.

**Comment by KevinHock** [comment]
I totally empathize with not having time to work on OSS -- I'm in the same boat.

Was this issue, the XSS,  fixed? Just trying to follow along from reading this issue and that part isn't clear to me. I could probably make a PR if it is not fixed.

**Comment by grahamgilbert** [comment]
The XSS was unverified and I wasn’t given enough information to reproduce.

**Comment by KevinHock** [comment]
Makes sense, I'd do the same in your situation, thanks Graham!!
